[{
	"question": "1 + 1?",
	"choiceA": "2",
	"choiceB": "1",
	"choiceC": "3",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "science",
	"difficulty": "1",
	"votes": 0,
	"upvotes": 0,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "What is the color of night?",
	"choiceA": "Black",
	"choiceB": "Your mother",
	"choiceC": "Sanguine",
	"choiceD": "-100",
	"correctAnswer": "C",
	"category": "video games",
	"difficulty": "3",
	"votes": 100,
	"upvotes": 100,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Do you like Roger Federer?",
	"choiceA": "Yes",
	"choiceB": "Yes",
	"choiceC": "Yes",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "sports",
	"difficulty": "1",
	"votes": 90,
	"upvotes": 90,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Is it wise to consume a gasconading sesquipedalian?",
	"choiceA": "Yes",
	"choiceB": "No",
	"choiceC": "Both of the above",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "science",
	"difficulty": "3",
	"votes": 1000,
	"upvotes": 1000,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Does the appearance of a rainbow-colored flamingo have any signifance in the Hamlet?",
	"choiceA": "Yes",
	"choiceB": "No",
	"choiceC": "There was no rainbow-colored flamingo",
	"choiceD": "-100",
	"correctAnswer": "C",
	"category": "literature",
	"difficulty": "2",
	"votes": 10,
	"upvotes": 10,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Is the Game of Thrones a show worth watching?",
	"choiceA": "No",
	"choiceB": "No",
	"choiceC": "No",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "movies and shows",
	"difficulty": "2",
	"votes": 20,
	"upvotes": 20,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "How old is Ash Ketchum?",
	"choiceA": "12",
	"choiceB": "10",
	"choiceC": "11",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "video games",
	"difficulty": "2",
	"votes": 85,
	"upvotes": 85,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Does global warming exist?",
	"choiceA": "Yes",
	"choiceB": "No",
	"choiceC": "Penguins",
	"choiceD": "-100",
	"correctAnswer": "B",
	"category": "science",
	"difficulty": "3",
	"votes": 400,
	"upvotes": 400,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
},
{
	"question": "Is Nadal on steriods?",
	"choiceA": "Yes",
	"choiceB": "Yes",
	"choiceC": "?",
	"choiceD": "-100",
	"correctAnswer": "A",
	"category": "sports",
	"difficulty": "1",
	"votes": 40,
	"upvotes": 40,
	"downvotes": 0,
	"usersVotedUp": [],
	"usersVotedDown": []
}]