[{
	"question": "1 + 1?",
	"choice-A": "2",
	"choice-B": "1",
	"choice-C": "3",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "science",
	"difficulty": "1",
	"upvotes": 0,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "What is the color of night?",
	"choice-A": "Black",
	"choice-B": "Your mother",
	"choice-C": "Sanguine",
	"choice-D": "-100",
	"correct-answer": "C",
	"category": "video games",
	"difficulty": "3",
	"upvotes": 100,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Do you like Roger Federer?",
	"choice-A": "Yes",
	"choice-B": "Yes",
	"choice-C": "Yes",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "sports",
	"difficulty": "1",
	"upvotes": 90,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Is it wise to consume a gasconading sesquipedalian?",
	"choice-A": "Yes",
	"choice-B": "No",
	"choice-C": "Both of the above",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "science",
	"difficulty": "3",
	"upvotes": 1000,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Does the appearance of a rainbow-colored flamingo have any signifance in the Hamlet?",
	"choice-A": "Yes",
	"choice-B": "No",
	"choice-C": "There was no rainbow-colored flamingo",
	"choice-D": "-100",
	"correct-answer": "C",
	"category": "literature",
	"difficulty": "2",
	"upvotes": 10,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Is the Game of Thrones a show worth watching?",
	"choice-A": "No",
	"choice-B": "No",
	"choice-C": "No",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "movies and shows",
	"difficulty": "2",
	"upvotes": 20,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "How old is Ash Ketchum?",
	"choice-A": "12",
	"choice-B": "10",
	"choice-C": "11",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "video games",
	"difficulty": "2",
	"upvotes": 85,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Does global warming exist?",
	"choice-A": "Yes",
	"choice-B": "No",
	"choice-C": "Penguins",
	"choice-D": "-100",
	"correct-answer": "B",
	"category": "science",
	"difficulty": "3",
	"upvotes": 400,
	"downvotes": 0,
	"usersVoted": []
},
{
	"question": "Is Nadal on steriods?",
	"choice-A": "Yes",
	"choice-B": "Yes",
	"choice-C": "?",
	"choice-D": "-100",
	"correct-answer": "A",
	"category": "sports",
	"difficulty": "1",
	"upvotes": 40,
	"downvotes": 0,
	"usersVoted": []
}]